'use strict';
const $=id=>document.getElementById(id);
const U={clamp:(v,a,b)=>v<a?a:(v>b?b:v),lerp:(a,b,t)=>a+(b-a)*t,rand:(a,b)=>a+Math.random()*(b-a),randi:n=>Math.floor(Math.random()*n),choice:a=>a[Math.floor(Math.random()*a.length)],approach(v,t,d){return v<t?Math.min(t,v+d):Math.max(t,v-d)}};
const Events={m:{},on(e,f){(this.m[e]=this.m[e]||[]).push(f)},emit(e,...a){(this.m[e]||[]).forEach(f=>f(...a))}};
const Store={KEY:'bloxhub_v1',data:null,load(){try{this.data=JSON.parse(localStorage.getItem(this.KEY))||{}}catch(e){this.data={}}if(!Array.isArray(this.data.owned))this.data.owned=[0];if(typeof this.data.coins!=='number')this.data.coins=0;if(typeof this.data.char!=='number')this.data.char=0;if(!this.data.best)this.data.best={};if(typeof this.data.muted!=='boolean')this.data.muted=false},save(){try{localStorage.setItem(this.KEY,JSON.stringify(this.data))}catch(e){}},addCoins(n){this.data.coins=Math.max(0,this.data.coins+n);this.save();Events.emit('coins')},setBest(id,score){const b=this.data.best[id]||0;if(score>b){this.data.best[id]=score;this.save();return true}return false},getBest(id){return this.data.best[id]||0}};
const Sfx={ctx:null,on:true,ensure(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(AC)this.ctx=new AC}if(this.ctx&&this.ctx.state==='suspended')this.ctx.resume()},tone(f,d,type,v,slide,when){if(!this.on)return;this.ensure();if(!this.ctx)return;type=type||'square';v=v||.12;when=when||0;const t=this.ctx.currentTime+when,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+d+.02)},click(){this.tone(620,.06)},jump(){this.tone(260,.18,'square',.11,240)},land(){this.tone(140,.08,'triangle',.09,-40)},coin(){this.tone(988,.07);this.tone(1319,.12,'square',.11,0,.07)},buy(){this.tone(523,.08);this.tone(784,.12,'square',.11,0,.08)},hit(){this.tone(150,.22,'sawtooth',.17,-90)},trap(){this.tone(220,.3,'sawtooth',.17,-160)},boom(){this.tone(90,.4,'sawtooth',.2,-60);this.tone(50,.5,'triangle',.2,-20,.02)},door(){this.tone(392,.1,'triangle');this.tone(523,.14,'triangle',.12,0,.09)},tap(){this.tone(740,.05,'triangle',.09)},level(){[523,659,784,1047].forEach((f,i)=>this.tone(f,.12,'square',.11,0,i*.08))},win(){[523,659,784,1047,1319].forEach((f,i)=>this.tone(f,.16,'square',.12,0,i*.1))},lose(){this.tone(330,.5,'sawtooth',.14,-200);this.tone(196,.6,'sawtooth',.11,-90,.2)}};
document.addEventListener('pointerdown',()=>Sfx.ensure());
const CHARS=[{name:'ÇAYLAK',skin:'#ffd23f',shirt:'#31a2ff',pants:'#274b7a',cost:0},{name:'NİNJA',skin:'#f2f2f2',shirt:'#23272e',pants:'#23272e',cost:60},{name:'İTFAİYECİ',skin:'#ffcf9e',shirt:'#ff5722',pants:'#37474f',cost:120},{name:'UZAYLI',skin:'#8be04a',shirt:'#9b59b6',pants:'#4a148c',cost:180},{name:'ROBO-PANDA',skin:'#fff',shirt:'#15181d',pants:'#15181d',cost:260},{name:'ALTIN KRAL',skin:'#ffd700',shirt:'#fff',pants:'#c0392b',cost:400}];
function avatarDOM(c){return '<div class="avo" style="--skin:'+c.skin+';--shirt:'+c.shirt+';--pants:'+c.pants+'"><div class="av-head"><div class="av-eye l"></div><div class="av-eye r"></div><div class="av-smile"></div></div><div class="av-row"><div class="av-arm"></div><div class="av-torso"></div><div class="av-arm"></div></div><div class="av-row2"><div class="av-leg"></div><div class="av-leg"></div></div></div>'}
